import { ReconciliationRow } from './ReconciliationScreen.hook';

export const RECONCILIATION_DUMMY_DATA: ReconciliationRow[] = [
  {
    id: '1',
    transactionNo: '08277549909',
    transactionType: 'EFT CREDIT',
    batchOwner: 'ICAN',
    accountName: 'MDL MD PC Deposits',
    payor: 'HEALTH NET COMMU',
    depositDate: '04/05/2026',
    bankDeposit: 819.72,
    remittance: 0,
    amd: 0,
    nextGenCore: 10,
    nextGenPcsd: 10,
    legacy: 0,
    gl: 0,
    unapplied: 0,
    variance: -819.72,
    status: 'Unreconciled',
    complexStatus: ['Remit missing', 'Post < Deposit', 'Age-276'],
    location: 'AZ',
    isEdited: true,
    comment: 'Check amount not matching'
  },
  {
    id: '2',
    transactionNo: 'W3272298...12',
    transactionType: 'EFT CREDIT',
    batchOwner: 'ICAN',
    accountName: 'MDL MD PC Deposits',
    payor: 'UnitedHealthcare',
    depositDate: '04/05/2026',
    bankDeposit: 742.69,
    remittance: 0,
    amd: 0,
    nextGenCore: 10,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 0,
    unapplied: 0,
    variance: -742.69,
    status: 'Unreconciled',
    complexStatus: ['Remit missing', 'Post < Deposit', 'Age-276'],
    location: 'CA',
    isEdited: false
  },
  {
    id: '3',
    transactionNo: 'T1122334...55',
    transactionType: 'CHECK',
    batchOwner: 'RECON',
    accountName: 'MDL MD PC Deposits',
    payor: 'UnitedHealthcare',
    depositDate: '04/04/2026',
    bankDeposit: 744.25,
    remittance: 744.25,
    amd: 0,
    nextGenCore: 744.25,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 0,
    unapplied: 0,
    variance: 0,
    status: 'Reconciled',
    complexStatus: ['Match', 'Age-30'],
    location: 'FL',
    reconcileDate: '04/04/2026'
  },
  {
    id: '4',
    transactionNo: '08277549910',
    transactionType: 'EFT CREDIT',
    batchOwner: 'ICAN',
    accountName: 'ST JOSEPH HEALTH',
    payor: 'AETNA HEALTH',
    depositDate: '04/04/2026',
    bankDeposit: 1540.50,
    remittance: 1540.50,
    amd: 1540.50,
    nextGenCore: 0,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 1540.50,
    unapplied: 0,
    variance: 0,
    status: 'Reconciled',
    complexStatus: ['Match'],
    location: 'TX',
    reconcileDate: '04/05/2026'
  },
  {
    id: '5',
    transactionNo: '08277549911',
    transactionType: 'CHECK',
    batchOwner: 'EXTERNAL',
    accountName: 'BAPTIST HEALTH',
    payor: 'BLUE CROSS BLUE SHIELD',
    depositDate: '04/03/2026',
    bankDeposit: 2100.00,
    remittance: 2000.00,
    amd: 0,
    nextGenCore: 2000.00,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 0,
    unapplied: 100.00,
    variance: -100.00,
    status: 'Unreconciled',
    complexStatus: ['Post < Deposit', 'Unapplied exists'],
    location: 'NC'
  },
  {
    id: '6',
    transactionNo: '08277549912',
    transactionType: 'EFT CREDIT',
    batchOwner: 'ICAN',
    accountName: 'MAYO CLINIC DEP',
    payor: 'CIGNA HEALTHCARE',
    depositDate: '04/03/2026',
    bankDeposit: 350.25,
    remittance: 350.25,
    amd: 0,
    nextGenCore: 350.25,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 350.25,
    unapplied: 0,
    variance: 0,
    status: 'Reconciled',
    complexStatus: ['Match'],
    location: 'MN',
    reconcileDate: '04/03/2026'
  },
  {
    id: '7',
    transactionNo: '08277549913',
    transactionType: 'CHECK',
    batchOwner: 'ICAN',
    accountName: 'CLEVELAND CLINIC',
    payor: 'MEDICARE OHIO',
    depositDate: '04/02/2026',
    bankDeposit: 12500.00,
    remittance: 0,
    amd: 0,
    nextGenCore: 0,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 0,
    unapplied: 0,
    variance: -12500.00,
    status: 'Unreconciled',
    complexStatus: ['Missing Remit', 'Age-60'],
    location: 'OH'
  },
  {
    id: '8',
    transactionNo: '08277549914',
    transactionType: 'EFT CREDIT',
    batchOwner: 'RECON_USER_1',
    accountName: 'DUKE UNIVERSITY',
    payor: 'MEDICAID NC',
    depositDate: '04/02/2026',
    bankDeposit: 4500.75,
    remittance: 4500.75,
    amd: 4500.75,
    nextGenCore: 4500.75,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 4500.75,
    unapplied: 0,
    variance: 0,
    status: 'Reconciled',
    complexStatus: ['Match'],
    location: 'NC',
    reconcileDate: '04/03/2026'
  },
  {
    id: '9',
    transactionNo: '08277549915',
    transactionType: 'CHECK',
    batchOwner: 'ICAN',
    accountName: 'MUSC HEALTH',
    payor: 'HUMANA',
    depositDate: '04/01/2026',
    bankDeposit: 890.00,
    remittance: 890.00,
    amd: 0,
    nextGenCore: 890.00,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 0,
    unapplied: 0,
    variance: 0,
    status: 'Reconciled',
    complexStatus: ['Match'],
    location: 'SC',
    reconcileDate: '04/01/2026'
  },
  {
    id: '10',
    transactionNo: '08277549916',
    transactionType: 'EFT CREDIT',
    batchOwner: 'ICAN',
    accountName: 'MDL MD PC Deposits',
    payor: 'KAISER PERMANENTE',
    depositDate: '04/01/2026',
    bankDeposit: 230.40,
    remittance: 0,
    amd: 0,
    nextGenCore: 0,
    nextGenPcsd: 0,
    legacy: 0,
    gl: 0,
    unapplied: 0,
    variance: -230.40,
    status: 'Unreconciled',
    complexStatus: ['Missing Remit', 'Age-90'],
    location: 'CA'
  }
];
